// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "webspam";
export const name = "witcherscript";
export const version = "0.4.3";
export const displayName = "WitcherScript";
export const description =
  "WitcherScript language support, with code completion, diagnostics, and more.";
export const extensionId = `${publisher}.${name}`;

/**
 * Type union of all commands
 */
export type CommandKey =
  | "witcherscript.restartServer"
  | "witcherscript.addLegacyScriptDirectory"
  | "witcherscript.addAdditionalScriptDirectory"
  | "witcherscript.openWalkthrough";

/**
 * Commands map registered by `webspam.witcherscript`
 */
export const commands = {
  /**
   * Restart Language Server
   * @value `witcherscript.restartServer`
   */
  restartServer: "witcherscript.restartServer",
  /**
   * Add Legacy Script Directory
   * @value `witcherscript.addLegacyScriptDirectory`
   */
  addLegacyScriptDirectory: "witcherscript.addLegacyScriptDirectory",
  /**
   * Add Additional Script Directory
   * @value `witcherscript.addAdditionalScriptDirectory`
   */
  addAdditionalScriptDirectory: "witcherscript.addAdditionalScriptDirectory",
  /**
   * Open Walkthrough
   * @value `witcherscript.openWalkthrough`
   */
  openWalkthrough: "witcherscript.openWalkthrough",
} satisfies Record<string, CommandKey>;

/**
 * Type union of all languages
 */
export type LanguageKey = "witcherscript";

/**
 * Languages map registed by `webspam.witcherscript`
 */
export const languages = {
  witcherscript: "witcherscript",
} satisfies Record<string, LanguageKey>;

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "witcherscript.gameDirectory"
  | "witcherscript.autoLoadModSharedImports"
  | "witcherscript.logLevel"
  | "witcherscript.diagnostics.scope"
  | "witcherscript.additionalScriptDirectories"
  | "witcherscript.legacyScriptDirectories"
  | "witcherscript.formatter.lineLimit"
  | "witcherscript.formatter.compactColon"
  | "witcherscript.formatter.alignMemberColons"
  | "witcherscript.server.path"
  | "witcherscript.server.tcpPort";

export interface ConfigKeyTypeMap {
  "witcherscript.gameDirectory": string;
  "witcherscript.autoLoadModSharedImports": boolean;
  "witcherscript.logLevel": "error" | "warn" | "info" | "debug" | "trace";
  "witcherscript.diagnostics.scope": "workspace" | "openFiles" | "none";
  "witcherscript.additionalScriptDirectories": string[];
  "witcherscript.legacyScriptDirectories": string[];
  "witcherscript.formatter.lineLimit": number;
  "witcherscript.formatter.compactColon": boolean;
  "witcherscript.formatter.alignMemberColons": boolean;
  "witcherscript.server.path": string;
  "witcherscript.server.tcpPort": number;
}

export interface ConfigShorthandMap {
  gameDirectory: "witcherscript.gameDirectory";
  autoLoadModSharedImports: "witcherscript.autoLoadModSharedImports";
  logLevel: "witcherscript.logLevel";
  diagnosticsScope: "witcherscript.diagnostics.scope";
  additionalScriptDirectories: "witcherscript.additionalScriptDirectories";
  legacyScriptDirectories: "witcherscript.legacyScriptDirectories";
  formatterLineLimit: "witcherscript.formatter.lineLimit";
  formatterCompactColon: "witcherscript.formatter.compactColon";
  formatterAlignMemberColons: "witcherscript.formatter.alignMemberColons";
  serverPath: "witcherscript.server.path";
  serverTcpPort: "witcherscript.server.tcpPort";
}

export interface ConfigShorthandTypeMap {
  gameDirectory: string;
  autoLoadModSharedImports: boolean;
  logLevel: "error" | "warn" | "info" | "debug" | "trace";
  diagnosticsScope: "workspace" | "openFiles" | "none";
  additionalScriptDirectories: string[];
  legacyScriptDirectories: string[];
  formatterLineLimit: number;
  formatterCompactColon: boolean;
  formatterAlignMemberColons: boolean;
  serverPath: string;
  serverTcpPort: number;
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T;
  default: ConfigKeyTypeMap[T];
}

/**
 * Configs map registered by `webspam.witcherscript`
 */
export const configs = {
  /**
   * Absolute path to The Witcher 3 game directory (e.g. C:\games\The Witcher 3 Wild Hunt GOTY). Used by the language server to locate base game scripts.
   * @key `witcherscript.gameDirectory`
   * @default `""`
   * @type `string`
   */
  gameDirectory: {
    key: "witcherscript.gameDirectory",
    default: "",
  } as ConfigItem<"witcherscript.gameDirectory">,
  /**
   * Auto-load the Shared Imports mod from <gameDirectory>\Mods\modSharedImports if present. Most modern Witcher 3 mods depend on it. Disable to opt out.
   * @key `witcherscript.autoLoadModSharedImports`
   * @default `true`
   * @type `boolean`
   */
  autoLoadModSharedImports: {
    key: "witcherscript.autoLoadModSharedImports",
    default: true,
  } as ConfigItem<"witcherscript.autoLoadModSharedImports">,
  /**
   * Log verbosity for the WitcherScript language server. Messages appear in the WitcherScript output channel.
   * @key `witcherscript.logLevel`
   * @default `"info"`
   * @type `string`
   */
  logLevel: {
    key: "witcherscript.logLevel",
    default: "info",
  } as ConfigItem<"witcherscript.logLevel">,
  /**
   *
   * @key `witcherscript.diagnostics.scope`
   * @default `"workspace"`
   * @type `string`
   */
  diagnosticsScope: {
    key: "witcherscript.diagnostics.scope",
    default: "workspace",
  } as ConfigItem<"witcherscript.diagnostics.scope">,
  /**
   *
   * @key `witcherscript.additionalScriptDirectories`
   * @default `[]`
   * @type `array`
   */
  additionalScriptDirectories: {
    key: "witcherscript.additionalScriptDirectories",
    default: [],
  } as ConfigItem<"witcherscript.additionalScriptDirectories">,
  /**
   *
   * @key `witcherscript.legacyScriptDirectories`
   * @default `[]`
   * @type `array`
   */
  legacyScriptDirectories: {
    key: "witcherscript.legacyScriptDirectories",
    default: [],
  } as ConfigItem<"witcherscript.legacyScriptDirectories">,
  /**
   * Maximum line length the formatter will target before wrapping.
   * @key `witcherscript.formatter.lineLimit`
   * @default `100`
   * @type `number`
   */
  formatterLineLimit: {
    key: "witcherscript.formatter.lineLimit",
    default: 100,
  } as ConfigItem<"witcherscript.formatter.lineLimit">,
  /**
   * When enabled, the formatter omits spaces around the colon in type annotations (e.g. `var x:int` instead of `var x : int`).
   * @key `witcherscript.formatter.compactColon`
   * @default `false`
   * @type `boolean`
   */
  formatterCompactColon: {
    key: "witcherscript.formatter.compactColon",
    default: false,
  } as ConfigItem<"witcherscript.formatter.compactColon">,
  /**
   * When enabled, the formatter vertically aligns the colons of consecutive class, struct, and state field declarations into a column. A blank line, comment, or non-field member breaks a group.
   * @key `witcherscript.formatter.alignMemberColons`
   * @default `false`
   * @type `boolean`
   */
  formatterAlignMemberColons: {
    key: "witcherscript.formatter.alignMemberColons",
    default: false,
  } as ConfigItem<"witcherscript.formatter.alignMemberColons">,
  /**
   * Optional path to the witcherscript-lsp executable. If empty, the extension uses the bundled server binary.
   * @key `witcherscript.server.path`
   * @default `""`
   * @type `string`
   */
  serverPath: {
    key: "witcherscript.server.path",
    default: "",
  } as ConfigItem<"witcherscript.server.path">,
  /**
   *
   * @key `witcherscript.server.tcpPort`
   * @default `0`
   * @type `number`
   */
  serverTcpPort: {
    key: "witcherscript.server.tcpPort",
    default: 0,
  } as ConfigItem<"witcherscript.server.tcpPort">,
};

export interface ScopedConfigKeyTypeMap {
  gameDirectory: string;
  autoLoadModSharedImports: boolean;
  logLevel: "error" | "warn" | "info" | "debug" | "trace";
  "diagnostics.scope": "workspace" | "openFiles" | "none";
  additionalScriptDirectories: string[];
  legacyScriptDirectories: string[];
  "formatter.lineLimit": number;
  "formatter.compactColon": boolean;
  "formatter.alignMemberColons": boolean;
  "server.path": string;
  "server.tcpPort": number;
}

export const scopedConfigs = {
  scope: "witcherscript",
  defaults: {
    gameDirectory: "",
    autoLoadModSharedImports: true,
    logLevel: "info",
    "diagnostics.scope": "workspace",
    additionalScriptDirectories: [],
    legacyScriptDirectories: [],
    "formatter.lineLimit": 100,
    "formatter.compactColon": false,
    "formatter.alignMemberColons": false,
    "server.path": "",
    "server.tcpPort": 0,
  } satisfies ScopedConfigKeyTypeMap,
};

export interface NestedConfigs {
  witcherscript: {
    gameDirectory: string;
    autoLoadModSharedImports: boolean;
    logLevel: "error" | "warn" | "info" | "debug" | "trace";
    diagnostics: {
      scope: "workspace" | "openFiles" | "none";
    };
    additionalScriptDirectories: string[];
    legacyScriptDirectories: string[];
    formatter: {
      lineLimit: number;
      compactColon: boolean;
      alignMemberColons: boolean;
    };
    server: {
      path: string;
      tcpPort: number;
    };
  };
}

export interface NestedScopedConfigs {
  gameDirectory: string;
  autoLoadModSharedImports: boolean;
  logLevel: "error" | "warn" | "info" | "debug" | "trace";
  diagnostics: {
    scope: "workspace" | "openFiles" | "none";
  };
  additionalScriptDirectories: string[];
  legacyScriptDirectories: string[];
  formatter: {
    lineLimit: number;
    compactColon: boolean;
    alignMemberColons: boolean;
  };
  server: {
    path: string;
    tcpPort: number;
  };
}
